spring:

  config:
    import: optional:file:.env[.properties]

  datasource:
    # url: ${MYSQL_URL}
    # username: ${MYSQL_USER}
    # password: ${MYSQL_PASSWORD}
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver # MySQL JDBC 드라이버 사용

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect # MySQL 문법 사용
    hibernate:
      ddl-auto: update # 실행 시 스키마 업데이트, 스키마 확정 시 validate
    show-sql: true # JPA가 실행하는 SQL 쿼리를 콘솔에 출력
    properties:
      hibernate:
        format_sql: true # SQL 쿼리를 보기 좋게 포맷팅하여 출력

server:
#  servlet:
#    session:
#      cookie:
#        name: JSESSIONID   # 세션 쿠키 이름 설정
#        secure: true      # HTTP 환경에서는 false, HTTPS 환경에서는 true
#        same-site: None    # SameSite=None 설정
  address: 0.0.0.0
  # port: 8080
